# Generated by Django 5.2.8 on 2025-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_colaborador_remove_epi_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=20),
        ),
    ]
