# Generated by Django 6.0 on 2025-12-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('validade', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.epi')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        )
    ]
